#!/usr/bin/env bash
#shellcheck disable=SC2086

my_bash_func()
{
if [ "$#" -eq 2 ];
then
dig $2.$1 | grep -A1 'ANSWER SECTION' | awk -v subdom=$2 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
else
dig $1 | grep -A1 'ANSWER SECTION' | awk -v subdom="www" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig $1 | grep -A1 'ANSWER SECTION' | awk -v subdom="lb-01" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig $1 | grep -A1 'ANSWER SECTION' | awk -v subdom="web-01" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig $1 | grep -A1 'ANSWER SECTION' | awk -v subdom="web-02" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
fi
}

#my_bash_func $1 $2

if [ "$#" -eq 2 ];
then
	my_bash_func $1 $2
else
	my_bash_func $1
fi
