#!/usr/bin/env bash
# Script to install nginx server
sudo apt update
sudo apt -y install nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
#sudo chown -R ubuntu /usr/share/nginx/html
#sudo chgrp -R ubuntu /usr/share/nginx/html
echo "Holberton School" > /usr/share/nginx/html/index.html
