#!/usr/bin/env bash
# Script to install nginx server
sudo apt update
sudo apt -y install nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
