#!/usr/bin/env bash
# Script to install nginx server
sudo apt update
sudo apt -y install nginx
sudo chown -R ubuntu /usr/share/nginx/html
sudo chgrp -R ubuntu /usr/share/nginx/html
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
