#!/usr/bin/env bash
# Script to install nginx server
sudo apt update
sudo apt -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "37i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
