#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
redirect301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "37i $redirect301" /etc/nginx/sites-available/default
sudo service nginx restart
