#!/usr/bin/env bash
# Script to install nginx server
sudo apt update
sudo apt -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
error="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-available/default
sudo sed -i "39i $error" /etc/nginx/sites-available/default
sudo service nginx restart
