#!/usr/bin/env bash
# Script to set http header
custom_header="\\\tadd_header X-Served-By \"$hostname\";\n"
sudo sed -i "17i $custom_header" /etc/nginx/nginx.conf
sudo service nginx restart
#sudo systemctl restart nginx.service
