#!/usr/bin/env bash
# script for print Fizz Buzz

counter=1

for ((counter; counter<=100; counter++))
do
	if ((counter % 3 == 0 && counter % 5 == 0))
	then
		echo "FizzBuzz"
	elif((counter % 3 == 0))
	then
		echo "Fizz"
	elif((counter % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
done
