#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

word="Holberton School"
greeting="Hi"
counter=0

while ((counter<10))
do
	if ((counter==9))
	then
		echo "$greeting"
	fi
	echo "$word"
	((counter++))
done
